name: Initialize Monorepo
description: Initialize nx monorepo for CI workflows

runs:
  using: 'composite'
  steps:
    - name: Use PNPM 9.x
      uses: pnpm/action-setup@v4
      with:
        version: 9
    - name: Use Node.js 20.x
      uses: actions/setup-node@v4
      with:
        node-version: 20
        cache: 'pnpm'
    - name: Install Node.js Dependencies
      shell: bash
      run: pnpm i --frozen-lockfile
    - uses: nrwl/nx-set-shas@v4