name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

permissions:
  pull-requests: write
  issues: write
  statuses: write
  checks: write
  contents: write

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: ./.github/actions/setup-monorepo
      - name: Build
        run: pnpm nx run-many --target build --all --output-style=stream
      - name: E2E Tests
        run: pnpm nx run @aws/nx-plugin-e2e:test
      - name: Coveralls
        uses: coverallsapp/github-action@v2
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
      - name: Release
        if: ${{ success() && (github.event_name != 'pull_request') }}
        env:
          NPM_TOKEN: ${{ secrets.NODE_AUTH_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          HUSKY: '0'
        run: |
          pnpm nx release --first-release